DWH_FINANCE:
  type: postgres
  host: ${AIF_DB_IP}
  port: 5432
  user: ${AIF_DB_USER}
  password: ${AIF_DB_SECRET}
  db_name: dwh_finance

DWH_USE_CASES:
  type: postgres
  host: ${AIF_DB_IP}
  port: 5432
  user: ${AIF_DB_USER}
  password: ${AIF_DB_SECRET}
  db_name: dwh_use_cases
